// Code generated by ent, DO NOT EDIT.

package mask

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the mask type in the database.
	Label = "mask"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldGUID holds the string denoting the guid field in the database.
	FieldGUID = "guid"
	// FieldThumbnailURL holds the string denoting the thumbnail_url field in the database.
	FieldThumbnailURL = "thumbnail_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeBundle holds the string denoting the bundle edge name in mutations.
	EdgeBundle = "bundle"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the mask in the database.
	Table = "masks"
	// BundleTable is the table that holds the bundle relation/edge.
	BundleTable = "bundles"
	// BundleInverseTable is the table name for the Bundle entity.
	// It exists in this package in order to avoid circular dependency with the "bundle" package.
	BundleInverseTable = "bundles"
	// BundleColumn is the table column denoting the bundle relation/edge.
	BundleColumn = "mask_id"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "masks"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
)

// Columns holds all SQL columns for mask fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldName,
	FieldDesc,
	FieldGUID,
	FieldThumbnailURL,
	FieldStatus,
	FieldType,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultDesc holds the default value on creation for the "desc" field.
	DefaultDesc string
	// DefaultThumbnailURL holds the default value on creation for the "thumbnail_url" field.
	DefaultThumbnailURL string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusStatus1 is the default value of the Status enum.
const DefaultStatus = StatusStatus1

// Status values.
const (
	StatusStatus1 Status = "status1"
	StatusStatus2 Status = "status2"
	StatusStatus3 Status = "status3"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusStatus1, StatusStatus2, StatusStatus3:
		return nil
	default:
		return fmt.Errorf("mask: invalid enum value for status field: %q", s)
	}
}

// Type defines the type for the "type" enum field.
type Type string

// TypeType1 is the default value of the Type enum.
const DefaultType = TypeType1

// Type values.
const (
	TypeType1 Type = "type1"
	TypeType2 Type = "type2"
	TypeType3 Type = "type3"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeType1, TypeType2, TypeType3:
		return nil
	default:
		return fmt.Errorf("mask: invalid enum value for type field: %q", _type)
	}
}
