// Code generated by ent, DO NOT EDIT.

package ent

import (
	"CSBackendTmp/ent/agora_token"
	"CSBackendTmp/ent/bundle"
	"CSBackendTmp/ent/card"
	"CSBackendTmp/ent/collection"
	"CSBackendTmp/ent/commodity"
	"CSBackendTmp/ent/contact"
	"CSBackendTmp/ent/creation"
	"CSBackendTmp/ent/csfield"
	"CSBackendTmp/ent/device"
	"CSBackendTmp/ent/feedback"
	"CSBackendTmp/ent/friendship"
	"CSBackendTmp/ent/hidden"
	"CSBackendTmp/ent/invite_code"
	"CSBackendTmp/ent/join"
	"CSBackendTmp/ent/mask"
	"CSBackendTmp/ent/message"
	"CSBackendTmp/ent/nft"
	"CSBackendTmp/ent/reaction"
	"CSBackendTmp/ent/rule"
	"CSBackendTmp/ent/schema"
	"CSBackendTmp/ent/setting"
	"CSBackendTmp/ent/stream"
	"CSBackendTmp/ent/timedew"
	"CSBackendTmp/ent/user"
	"CSBackendTmp/ent/user_auth"
	"CSBackendTmp/ent/user_history"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agora_tokenMixin := schema.Agora_token{}.Mixin()
	agora_tokenMixinFields0 := agora_tokenMixin[0].Fields()
	_ = agora_tokenMixinFields0
	agora_tokenFields := schema.Agora_token{}.Fields()
	_ = agora_tokenFields
	// agora_tokenDescCreateTime is the schema descriptor for create_time field.
	agora_tokenDescCreateTime := agora_tokenMixinFields0[0].Descriptor()
	// agora_token.DefaultCreateTime holds the default value on creation for the create_time field.
	agora_token.DefaultCreateTime = agora_tokenDescCreateTime.Default.(func() time.Time)
	// agora_tokenDescUpdateTime is the schema descriptor for update_time field.
	agora_tokenDescUpdateTime := agora_tokenMixinFields0[1].Descriptor()
	// agora_token.DefaultUpdateTime holds the default value on creation for the update_time field.
	agora_token.DefaultUpdateTime = agora_tokenDescUpdateTime.Default.(func() time.Time)
	// agora_token.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	agora_token.UpdateDefaultUpdateTime = agora_tokenDescUpdateTime.UpdateDefault.(func() time.Time)
	bundleMixin := schema.Bundle{}.Mixin()
	bundleMixinFields0 := bundleMixin[0].Fields()
	_ = bundleMixinFields0
	bundleFields := schema.Bundle{}.Fields()
	_ = bundleFields
	// bundleDescCreateTime is the schema descriptor for create_time field.
	bundleDescCreateTime := bundleMixinFields0[0].Descriptor()
	// bundle.DefaultCreateTime holds the default value on creation for the create_time field.
	bundle.DefaultCreateTime = bundleDescCreateTime.Default.(func() time.Time)
	// bundleDescUpdateTime is the schema descriptor for update_time field.
	bundleDescUpdateTime := bundleMixinFields0[1].Descriptor()
	// bundle.DefaultUpdateTime holds the default value on creation for the update_time field.
	bundle.DefaultUpdateTime = bundleDescUpdateTime.Default.(func() time.Time)
	// bundle.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	bundle.UpdateDefaultUpdateTime = bundleDescUpdateTime.UpdateDefault.(func() time.Time)
	csfieldMixin := schema.CSField{}.Mixin()
	csfieldMixinFields0 := csfieldMixin[0].Fields()
	_ = csfieldMixinFields0
	csfieldFields := schema.CSField{}.Fields()
	_ = csfieldFields
	// csfieldDescCreateTime is the schema descriptor for create_time field.
	csfieldDescCreateTime := csfieldMixinFields0[0].Descriptor()
	// csfield.DefaultCreateTime holds the default value on creation for the create_time field.
	csfield.DefaultCreateTime = csfieldDescCreateTime.Default.(func() time.Time)
	// csfieldDescUpdateTime is the schema descriptor for update_time field.
	csfieldDescUpdateTime := csfieldMixinFields0[1].Descriptor()
	// csfield.DefaultUpdateTime holds the default value on creation for the update_time field.
	csfield.DefaultUpdateTime = csfieldDescUpdateTime.Default.(func() time.Time)
	// csfield.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	csfield.UpdateDefaultUpdateTime = csfieldDescUpdateTime.UpdateDefault.(func() time.Time)
	cardMixin := schema.Card{}.Mixin()
	cardMixinFields0 := cardMixin[0].Fields()
	_ = cardMixinFields0
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescCreateTime is the schema descriptor for create_time field.
	cardDescCreateTime := cardMixinFields0[0].Descriptor()
	// card.DefaultCreateTime holds the default value on creation for the create_time field.
	card.DefaultCreateTime = cardDescCreateTime.Default.(func() time.Time)
	// cardDescUpdateTime is the schema descriptor for update_time field.
	cardDescUpdateTime := cardMixinFields0[1].Descriptor()
	// card.DefaultUpdateTime holds the default value on creation for the update_time field.
	card.DefaultUpdateTime = cardDescUpdateTime.Default.(func() time.Time)
	// card.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	card.UpdateDefaultUpdateTime = cardDescUpdateTime.UpdateDefault.(func() time.Time)
	collectionMixin := schema.Collection{}.Mixin()
	collectionMixinFields0 := collectionMixin[0].Fields()
	_ = collectionMixinFields0
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescCreateTime is the schema descriptor for create_time field.
	collectionDescCreateTime := collectionMixinFields0[0].Descriptor()
	// collection.DefaultCreateTime holds the default value on creation for the create_time field.
	collection.DefaultCreateTime = collectionDescCreateTime.Default.(func() time.Time)
	// collectionDescUpdateTime is the schema descriptor for update_time field.
	collectionDescUpdateTime := collectionMixinFields0[1].Descriptor()
	// collection.DefaultUpdateTime holds the default value on creation for the update_time field.
	collection.DefaultUpdateTime = collectionDescUpdateTime.Default.(func() time.Time)
	// collection.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	collection.UpdateDefaultUpdateTime = collectionDescUpdateTime.UpdateDefault.(func() time.Time)
	commodityMixin := schema.Commodity{}.Mixin()
	commodityMixinFields0 := commodityMixin[0].Fields()
	_ = commodityMixinFields0
	commodityFields := schema.Commodity{}.Fields()
	_ = commodityFields
	// commodityDescCreateTime is the schema descriptor for create_time field.
	commodityDescCreateTime := commodityMixinFields0[0].Descriptor()
	// commodity.DefaultCreateTime holds the default value on creation for the create_time field.
	commodity.DefaultCreateTime = commodityDescCreateTime.Default.(func() time.Time)
	// commodityDescUpdateTime is the schema descriptor for update_time field.
	commodityDescUpdateTime := commodityMixinFields0[1].Descriptor()
	// commodity.DefaultUpdateTime holds the default value on creation for the update_time field.
	commodity.DefaultUpdateTime = commodityDescUpdateTime.Default.(func() time.Time)
	// commodity.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	commodity.UpdateDefaultUpdateTime = commodityDescUpdateTime.UpdateDefault.(func() time.Time)
	contactMixin := schema.Contact{}.Mixin()
	contactMixinFields0 := contactMixin[0].Fields()
	_ = contactMixinFields0
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescCreateTime is the schema descriptor for create_time field.
	contactDescCreateTime := contactMixinFields0[0].Descriptor()
	// contact.DefaultCreateTime holds the default value on creation for the create_time field.
	contact.DefaultCreateTime = contactDescCreateTime.Default.(func() time.Time)
	// contactDescUpdateTime is the schema descriptor for update_time field.
	contactDescUpdateTime := contactMixinFields0[1].Descriptor()
	// contact.DefaultUpdateTime holds the default value on creation for the update_time field.
	contact.DefaultUpdateTime = contactDescUpdateTime.Default.(func() time.Time)
	// contact.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	contact.UpdateDefaultUpdateTime = contactDescUpdateTime.UpdateDefault.(func() time.Time)
	creationMixin := schema.Creation{}.Mixin()
	creationMixinFields0 := creationMixin[0].Fields()
	_ = creationMixinFields0
	creationFields := schema.Creation{}.Fields()
	_ = creationFields
	// creationDescCreateTime is the schema descriptor for create_time field.
	creationDescCreateTime := creationMixinFields0[0].Descriptor()
	// creation.DefaultCreateTime holds the default value on creation for the create_time field.
	creation.DefaultCreateTime = creationDescCreateTime.Default.(func() time.Time)
	// creationDescUpdateTime is the schema descriptor for update_time field.
	creationDescUpdateTime := creationMixinFields0[1].Descriptor()
	// creation.DefaultUpdateTime holds the default value on creation for the update_time field.
	creation.DefaultUpdateTime = creationDescUpdateTime.Default.(func() time.Time)
	// creation.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	creation.UpdateDefaultUpdateTime = creationDescUpdateTime.UpdateDefault.(func() time.Time)
	deviceMixin := schema.Device{}.Mixin()
	deviceMixinFields0 := deviceMixin[0].Fields()
	_ = deviceMixinFields0
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescCreateTime is the schema descriptor for create_time field.
	deviceDescCreateTime := deviceMixinFields0[0].Descriptor()
	// device.DefaultCreateTime holds the default value on creation for the create_time field.
	device.DefaultCreateTime = deviceDescCreateTime.Default.(func() time.Time)
	// deviceDescUpdateTime is the schema descriptor for update_time field.
	deviceDescUpdateTime := deviceMixinFields0[1].Descriptor()
	// device.DefaultUpdateTime holds the default value on creation for the update_time field.
	device.DefaultUpdateTime = deviceDescUpdateTime.Default.(func() time.Time)
	// device.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	device.UpdateDefaultUpdateTime = deviceDescUpdateTime.UpdateDefault.(func() time.Time)
	feedbackMixin := schema.Feedback{}.Mixin()
	feedbackMixinFields0 := feedbackMixin[0].Fields()
	_ = feedbackMixinFields0
	feedbackFields := schema.Feedback{}.Fields()
	_ = feedbackFields
	// feedbackDescCreateTime is the schema descriptor for create_time field.
	feedbackDescCreateTime := feedbackMixinFields0[0].Descriptor()
	// feedback.DefaultCreateTime holds the default value on creation for the create_time field.
	feedback.DefaultCreateTime = feedbackDescCreateTime.Default.(func() time.Time)
	// feedbackDescUpdateTime is the schema descriptor for update_time field.
	feedbackDescUpdateTime := feedbackMixinFields0[1].Descriptor()
	// feedback.DefaultUpdateTime holds the default value on creation for the update_time field.
	feedback.DefaultUpdateTime = feedbackDescUpdateTime.Default.(func() time.Time)
	// feedback.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	feedback.UpdateDefaultUpdateTime = feedbackDescUpdateTime.UpdateDefault.(func() time.Time)
	friendshipMixin := schema.Friendship{}.Mixin()
	friendshipMixinFields0 := friendshipMixin[0].Fields()
	_ = friendshipMixinFields0
	friendshipFields := schema.Friendship{}.Fields()
	_ = friendshipFields
	// friendshipDescCreateTime is the schema descriptor for create_time field.
	friendshipDescCreateTime := friendshipMixinFields0[0].Descriptor()
	// friendship.DefaultCreateTime holds the default value on creation for the create_time field.
	friendship.DefaultCreateTime = friendshipDescCreateTime.Default.(func() time.Time)
	// friendshipDescUpdateTime is the schema descriptor for update_time field.
	friendshipDescUpdateTime := friendshipMixinFields0[1].Descriptor()
	// friendship.DefaultUpdateTime holds the default value on creation for the update_time field.
	friendship.DefaultUpdateTime = friendshipDescUpdateTime.Default.(func() time.Time)
	// friendship.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	friendship.UpdateDefaultUpdateTime = friendshipDescUpdateTime.UpdateDefault.(func() time.Time)
	hiddenMixin := schema.Hidden{}.Mixin()
	hiddenMixinFields0 := hiddenMixin[0].Fields()
	_ = hiddenMixinFields0
	hiddenFields := schema.Hidden{}.Fields()
	_ = hiddenFields
	// hiddenDescCreateTime is the schema descriptor for create_time field.
	hiddenDescCreateTime := hiddenMixinFields0[0].Descriptor()
	// hidden.DefaultCreateTime holds the default value on creation for the create_time field.
	hidden.DefaultCreateTime = hiddenDescCreateTime.Default.(func() time.Time)
	// hiddenDescUpdateTime is the schema descriptor for update_time field.
	hiddenDescUpdateTime := hiddenMixinFields0[1].Descriptor()
	// hidden.DefaultUpdateTime holds the default value on creation for the update_time field.
	hidden.DefaultUpdateTime = hiddenDescUpdateTime.Default.(func() time.Time)
	// hidden.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	hidden.UpdateDefaultUpdateTime = hiddenDescUpdateTime.UpdateDefault.(func() time.Time)
	invite_codeMixin := schema.Invite_Code{}.Mixin()
	invite_codeMixinFields0 := invite_codeMixin[0].Fields()
	_ = invite_codeMixinFields0
	invite_codeFields := schema.Invite_Code{}.Fields()
	_ = invite_codeFields
	// invite_codeDescCreateTime is the schema descriptor for create_time field.
	invite_codeDescCreateTime := invite_codeMixinFields0[0].Descriptor()
	// invite_code.DefaultCreateTime holds the default value on creation for the create_time field.
	invite_code.DefaultCreateTime = invite_codeDescCreateTime.Default.(func() time.Time)
	// invite_codeDescUpdateTime is the schema descriptor for update_time field.
	invite_codeDescUpdateTime := invite_codeMixinFields0[1].Descriptor()
	// invite_code.DefaultUpdateTime holds the default value on creation for the update_time field.
	invite_code.DefaultUpdateTime = invite_codeDescUpdateTime.Default.(func() time.Time)
	// invite_code.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	invite_code.UpdateDefaultUpdateTime = invite_codeDescUpdateTime.UpdateDefault.(func() time.Time)
	joinMixin := schema.Join{}.Mixin()
	joinMixinFields0 := joinMixin[0].Fields()
	_ = joinMixinFields0
	joinFields := schema.Join{}.Fields()
	_ = joinFields
	// joinDescCreateTime is the schema descriptor for create_time field.
	joinDescCreateTime := joinMixinFields0[0].Descriptor()
	// join.DefaultCreateTime holds the default value on creation for the create_time field.
	join.DefaultCreateTime = joinDescCreateTime.Default.(func() time.Time)
	// joinDescUpdateTime is the schema descriptor for update_time field.
	joinDescUpdateTime := joinMixinFields0[1].Descriptor()
	// join.DefaultUpdateTime holds the default value on creation for the update_time field.
	join.DefaultUpdateTime = joinDescUpdateTime.Default.(func() time.Time)
	// join.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	join.UpdateDefaultUpdateTime = joinDescUpdateTime.UpdateDefault.(func() time.Time)
	// joinDescJoinAt is the schema descriptor for join_at field.
	joinDescJoinAt := joinFields[0].Descriptor()
	// join.DefaultJoinAt holds the default value on creation for the join_at field.
	join.DefaultJoinAt = joinDescJoinAt.Default.(func() time.Time)
	maskMixin := schema.Mask{}.Mixin()
	maskMixinFields0 := maskMixin[0].Fields()
	_ = maskMixinFields0
	maskFields := schema.Mask{}.Fields()
	_ = maskFields
	// maskDescCreateTime is the schema descriptor for create_time field.
	maskDescCreateTime := maskMixinFields0[0].Descriptor()
	// mask.DefaultCreateTime holds the default value on creation for the create_time field.
	mask.DefaultCreateTime = maskDescCreateTime.Default.(func() time.Time)
	// maskDescUpdateTime is the schema descriptor for update_time field.
	maskDescUpdateTime := maskMixinFields0[1].Descriptor()
	// mask.DefaultUpdateTime holds the default value on creation for the update_time field.
	mask.DefaultUpdateTime = maskDescUpdateTime.Default.(func() time.Time)
	// mask.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	mask.UpdateDefaultUpdateTime = maskDescUpdateTime.UpdateDefault.(func() time.Time)
	// maskDescDesc is the schema descriptor for desc field.
	maskDescDesc := maskFields[2].Descriptor()
	// mask.DefaultDesc holds the default value on creation for the desc field.
	mask.DefaultDesc = maskDescDesc.Default.(string)
	// maskDescThumbnailURL is the schema descriptor for thumbnail_url field.
	maskDescThumbnailURL := maskFields[4].Descriptor()
	// mask.DefaultThumbnailURL holds the default value on creation for the thumbnail_url field.
	mask.DefaultThumbnailURL = maskDescThumbnailURL.Default.(string)
	messageMixin := schema.Message{}.Mixin()
	messageMixinFields0 := messageMixin[0].Fields()
	_ = messageMixinFields0
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreateTime is the schema descriptor for create_time field.
	messageDescCreateTime := messageMixinFields0[0].Descriptor()
	// message.DefaultCreateTime holds the default value on creation for the create_time field.
	message.DefaultCreateTime = messageDescCreateTime.Default.(func() time.Time)
	// messageDescUpdateTime is the schema descriptor for update_time field.
	messageDescUpdateTime := messageMixinFields0[1].Descriptor()
	// message.DefaultUpdateTime holds the default value on creation for the update_time field.
	message.DefaultUpdateTime = messageDescUpdateTime.Default.(func() time.Time)
	// message.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	message.UpdateDefaultUpdateTime = messageDescUpdateTime.UpdateDefault.(func() time.Time)
	nftMixin := schema.NFT{}.Mixin()
	nftMixinFields0 := nftMixin[0].Fields()
	_ = nftMixinFields0
	nftFields := schema.NFT{}.Fields()
	_ = nftFields
	// nftDescCreateTime is the schema descriptor for create_time field.
	nftDescCreateTime := nftMixinFields0[0].Descriptor()
	// nft.DefaultCreateTime holds the default value on creation for the create_time field.
	nft.DefaultCreateTime = nftDescCreateTime.Default.(func() time.Time)
	// nftDescUpdateTime is the schema descriptor for update_time field.
	nftDescUpdateTime := nftMixinFields0[1].Descriptor()
	// nft.DefaultUpdateTime holds the default value on creation for the update_time field.
	nft.DefaultUpdateTime = nftDescUpdateTime.Default.(func() time.Time)
	// nft.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	nft.UpdateDefaultUpdateTime = nftDescUpdateTime.UpdateDefault.(func() time.Time)
	// nftDescName is the schema descriptor for name field.
	nftDescName := nftFields[1].Descriptor()
	// nft.DefaultName holds the default value on creation for the name field.
	nft.DefaultName = nftDescName.Default.(string)
	// nftDescDesc is the schema descriptor for desc field.
	nftDescDesc := nftFields[2].Descriptor()
	// nft.DefaultDesc holds the default value on creation for the desc field.
	nft.DefaultDesc = nftDescDesc.Default.(string)
	// nftDescContractAddress is the schema descriptor for contract_address field.
	nftDescContractAddress := nftFields[13].Descriptor()
	// nft.DefaultContractAddress holds the default value on creation for the contract_address field.
	nft.DefaultContractAddress = nftDescContractAddress.Default.(string)
	// nftDescMintCardNum is the schema descriptor for mint_card_num field.
	nftDescMintCardNum := nftFields[14].Descriptor()
	// nft.DefaultMintCardNum holds the default value on creation for the mint_card_num field.
	nft.DefaultMintCardNum = nftDescMintCardNum.Default.(uint64)
	reactionMixin := schema.Reaction{}.Mixin()
	reactionMixinFields0 := reactionMixin[0].Fields()
	_ = reactionMixinFields0
	reactionFields := schema.Reaction{}.Fields()
	_ = reactionFields
	// reactionDescCreateTime is the schema descriptor for create_time field.
	reactionDescCreateTime := reactionMixinFields0[0].Descriptor()
	// reaction.DefaultCreateTime holds the default value on creation for the create_time field.
	reaction.DefaultCreateTime = reactionDescCreateTime.Default.(func() time.Time)
	// reactionDescUpdateTime is the schema descriptor for update_time field.
	reactionDescUpdateTime := reactionMixinFields0[1].Descriptor()
	// reaction.DefaultUpdateTime holds the default value on creation for the update_time field.
	reaction.DefaultUpdateTime = reactionDescUpdateTime.Default.(func() time.Time)
	// reaction.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	reaction.UpdateDefaultUpdateTime = reactionDescUpdateTime.UpdateDefault.(func() time.Time)
	// reactionDescIsLOL is the schema descriptor for isLOL field.
	reactionDescIsLOL := reactionFields[0].Descriptor()
	// reaction.DefaultIsLOL holds the default value on creation for the isLOL field.
	reaction.DefaultIsLOL = reactionDescIsLOL.Default.(bool)
	// reactionDescIsOMG is the schema descriptor for isOMG field.
	reactionDescIsOMG := reactionFields[1].Descriptor()
	// reaction.DefaultIsOMG holds the default value on creation for the isOMG field.
	reaction.DefaultIsOMG = reactionDescIsOMG.Default.(bool)
	// reactionDescIsCool is the schema descriptor for isCool field.
	reactionDescIsCool := reactionFields[2].Descriptor()
	// reaction.DefaultIsCool holds the default value on creation for the isCool field.
	reaction.DefaultIsCool = reactionDescIsCool.Default.(bool)
	// reactionDescIsNooo is the schema descriptor for isNooo field.
	reactionDescIsNooo := reactionFields[3].Descriptor()
	// reaction.DefaultIsNooo holds the default value on creation for the isNooo field.
	reaction.DefaultIsNooo = reactionDescIsNooo.Default.(bool)
	// reactionDescIsDAMN is the schema descriptor for isDAMN field.
	reactionDescIsDAMN := reactionFields[4].Descriptor()
	// reaction.DefaultIsDAMN holds the default value on creation for the isDAMN field.
	reaction.DefaultIsDAMN = reactionDescIsDAMN.Default.(bool)
	ruleMixin := schema.Rule{}.Mixin()
	ruleMixinFields0 := ruleMixin[0].Fields()
	_ = ruleMixinFields0
	ruleFields := schema.Rule{}.Fields()
	_ = ruleFields
	// ruleDescCreateTime is the schema descriptor for create_time field.
	ruleDescCreateTime := ruleMixinFields0[0].Descriptor()
	// rule.DefaultCreateTime holds the default value on creation for the create_time field.
	rule.DefaultCreateTime = ruleDescCreateTime.Default.(func() time.Time)
	// ruleDescUpdateTime is the schema descriptor for update_time field.
	ruleDescUpdateTime := ruleMixinFields0[1].Descriptor()
	// rule.DefaultUpdateTime holds the default value on creation for the update_time field.
	rule.DefaultUpdateTime = ruleDescUpdateTime.Default.(func() time.Time)
	// rule.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	rule.UpdateDefaultUpdateTime = ruleDescUpdateTime.UpdateDefault.(func() time.Time)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreateTime is the schema descriptor for create_time field.
	settingDescCreateTime := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreateTime holds the default value on creation for the create_time field.
	setting.DefaultCreateTime = settingDescCreateTime.Default.(func() time.Time)
	// settingDescUpdateTime is the schema descriptor for update_time field.
	settingDescUpdateTime := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdateTime holds the default value on creation for the update_time field.
	setting.DefaultUpdateTime = settingDescUpdateTime.Default.(func() time.Time)
	// setting.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	setting.UpdateDefaultUpdateTime = settingDescUpdateTime.UpdateDefault.(func() time.Time)
	// settingDescFriendsOnline is the schema descriptor for friends_online field.
	settingDescFriendsOnline := settingFields[1].Descriptor()
	// setting.DefaultFriendsOnline holds the default value on creation for the friends_online field.
	setting.DefaultFriendsOnline = settingDescFriendsOnline.Default.(bool)
	// settingDescTimeDewFromFriends is the schema descriptor for time_dew_from_friends field.
	settingDescTimeDewFromFriends := settingFields[2].Descriptor()
	// setting.DefaultTimeDewFromFriends holds the default value on creation for the time_dew_from_friends field.
	setting.DefaultTimeDewFromFriends = settingDescTimeDewFromFriends.Default.(bool)
	// settingDescDetailedNotification is the schema descriptor for detailed_notification field.
	settingDescDetailedNotification := settingFields[3].Descriptor()
	// setting.DefaultDetailedNotification holds the default value on creation for the detailed_notification field.
	setting.DefaultDetailedNotification = settingDescDetailedNotification.Default.(bool)
	// settingDescReceiveFieldInvitation is the schema descriptor for receive_field_invitation field.
	settingDescReceiveFieldInvitation := settingFields[4].Descriptor()
	// setting.DefaultReceiveFieldInvitation holds the default value on creation for the receive_field_invitation field.
	setting.DefaultReceiveFieldInvitation = settingDescReceiveFieldInvitation.Default.(bool)
	// settingDescSeeMyLocation is the schema descriptor for see_my_location field.
	settingDescSeeMyLocation := settingFields[5].Descriptor()
	// setting.DefaultSeeMyLocation holds the default value on creation for the see_my_location field.
	setting.DefaultSeeMyLocation = settingDescSeeMyLocation.Default.(bool)
	// settingDescCamera is the schema descriptor for camera field.
	settingDescCamera := settingFields[6].Descriptor()
	// setting.DefaultCamera holds the default value on creation for the camera field.
	setting.DefaultCamera = settingDescCamera.Default.(bool)
	// settingDescMicrophone is the schema descriptor for microphone field.
	settingDescMicrophone := settingFields[7].Descriptor()
	// setting.DefaultMicrophone holds the default value on creation for the microphone field.
	setting.DefaultMicrophone = settingDescMicrophone.Default.(bool)
	// settingDescHealthData is the schema descriptor for health_data field.
	settingDescHealthData := settingFields[8].Descriptor()
	// setting.DefaultHealthData holds the default value on creation for the health_data field.
	setting.DefaultHealthData = settingDescHealthData.Default.(bool)
	// settingDescTimeDewLocation is the schema descriptor for time_dew_location field.
	settingDescTimeDewLocation := settingFields[9].Descriptor()
	// setting.DefaultTimeDewLocation holds the default value on creation for the time_dew_location field.
	setting.DefaultTimeDewLocation = settingDescTimeDewLocation.Default.(bool)
	// settingDescTimeDewMicrophone is the schema descriptor for time_dew_microphone field.
	settingDescTimeDewMicrophone := settingFields[10].Descriptor()
	// setting.DefaultTimeDewMicrophone holds the default value on creation for the time_dew_microphone field.
	setting.DefaultTimeDewMicrophone = settingDescTimeDewMicrophone.Default.(bool)
	// settingDescTimeDewLora is the schema descriptor for time_dew_Lora field.
	settingDescTimeDewLora := settingFields[11].Descriptor()
	// setting.DefaultTimeDewLora holds the default value on creation for the time_dew_Lora field.
	setting.DefaultTimeDewLora = settingDescTimeDewLora.Default.(bool)
	// settingDescPublicCollection is the schema descriptor for public_collection field.
	settingDescPublicCollection := settingFields[12].Descriptor()
	// setting.DefaultPublicCollection holds the default value on creation for the public_collection field.
	setting.DefaultPublicCollection = settingDescPublicCollection.Default.(bool)
	streamMixin := schema.Stream{}.Mixin()
	streamMixinFields0 := streamMixin[0].Fields()
	_ = streamMixinFields0
	streamFields := schema.Stream{}.Fields()
	_ = streamFields
	// streamDescCreateTime is the schema descriptor for create_time field.
	streamDescCreateTime := streamMixinFields0[0].Descriptor()
	// stream.DefaultCreateTime holds the default value on creation for the create_time field.
	stream.DefaultCreateTime = streamDescCreateTime.Default.(func() time.Time)
	// streamDescUpdateTime is the schema descriptor for update_time field.
	streamDescUpdateTime := streamMixinFields0[1].Descriptor()
	// stream.DefaultUpdateTime holds the default value on creation for the update_time field.
	stream.DefaultUpdateTime = streamDescUpdateTime.Default.(func() time.Time)
	// stream.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	stream.UpdateDefaultUpdateTime = streamDescUpdateTime.UpdateDefault.(func() time.Time)
	timedewMixin := schema.TimeDew{}.Mixin()
	timedewMixinFields0 := timedewMixin[0].Fields()
	_ = timedewMixinFields0
	timedewFields := schema.TimeDew{}.Fields()
	_ = timedewFields
	// timedewDescCreateTime is the schema descriptor for create_time field.
	timedewDescCreateTime := timedewMixinFields0[0].Descriptor()
	// timedew.DefaultCreateTime holds the default value on creation for the create_time field.
	timedew.DefaultCreateTime = timedewDescCreateTime.Default.(func() time.Time)
	// timedewDescUpdateTime is the schema descriptor for update_time field.
	timedewDescUpdateTime := timedewMixinFields0[1].Descriptor()
	// timedew.DefaultUpdateTime holds the default value on creation for the update_time field.
	timedew.DefaultUpdateTime = timedewDescUpdateTime.Default.(func() time.Time)
	// timedew.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	timedew.UpdateDefaultUpdateTime = timedewDescUpdateTime.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescThumbnailURL is the schema descriptor for thumbnail_url field.
	userDescThumbnailURL := userFields[6].Descriptor()
	// user.DefaultThumbnailURL holds the default value on creation for the thumbnail_url field.
	user.DefaultThumbnailURL = userDescThumbnailURL.Default.(string)
	// userDescIsShowCollections is the schema descriptor for is_show_collections field.
	userDescIsShowCollections := userFields[17].Descriptor()
	// user.DefaultIsShowCollections holds the default value on creation for the is_show_collections field.
	user.DefaultIsShowCollections = userDescIsShowCollections.Default.(bool)
	// userDescIsInvited is the schema descriptor for is_invited field.
	userDescIsInvited := userFields[18].Descriptor()
	// user.DefaultIsInvited holds the default value on creation for the is_invited field.
	user.DefaultIsInvited = userDescIsInvited.Default.(bool)
	// userDescNeedPrivacyConfirm is the schema descriptor for need_privacy_confirm field.
	userDescNeedPrivacyConfirm := userFields[19].Descriptor()
	// user.DefaultNeedPrivacyConfirm holds the default value on creation for the need_privacy_confirm field.
	user.DefaultNeedPrivacyConfirm = userDescNeedPrivacyConfirm.Default.(bool)
	user_authMixin := schema.User_auth{}.Mixin()
	user_authMixinFields0 := user_authMixin[0].Fields()
	_ = user_authMixinFields0
	user_authFields := schema.User_auth{}.Fields()
	_ = user_authFields
	// user_authDescCreateTime is the schema descriptor for create_time field.
	user_authDescCreateTime := user_authMixinFields0[0].Descriptor()
	// user_auth.DefaultCreateTime holds the default value on creation for the create_time field.
	user_auth.DefaultCreateTime = user_authDescCreateTime.Default.(func() time.Time)
	// user_authDescUpdateTime is the schema descriptor for update_time field.
	user_authDescUpdateTime := user_authMixinFields0[1].Descriptor()
	// user_auth.DefaultUpdateTime holds the default value on creation for the update_time field.
	user_auth.DefaultUpdateTime = user_authDescUpdateTime.Default.(func() time.Time)
	// user_auth.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user_auth.UpdateDefaultUpdateTime = user_authDescUpdateTime.UpdateDefault.(func() time.Time)
	user_historyMixin := schema.User_history{}.Mixin()
	user_historyMixinFields0 := user_historyMixin[0].Fields()
	_ = user_historyMixinFields0
	user_historyFields := schema.User_history{}.Fields()
	_ = user_historyFields
	// user_historyDescCreateTime is the schema descriptor for create_time field.
	user_historyDescCreateTime := user_historyMixinFields0[0].Descriptor()
	// user_history.DefaultCreateTime holds the default value on creation for the create_time field.
	user_history.DefaultCreateTime = user_historyDescCreateTime.Default.(func() time.Time)
	// user_historyDescUpdateTime is the schema descriptor for update_time field.
	user_historyDescUpdateTime := user_historyMixinFields0[1].Descriptor()
	// user_history.DefaultUpdateTime holds the default value on creation for the update_time field.
	user_history.DefaultUpdateTime = user_historyDescUpdateTime.Default.(func() time.Time)
	// user_history.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user_history.UpdateDefaultUpdateTime = user_historyDescUpdateTime.UpdateDefault.(func() time.Time)
}
